version: '2'

services:
  db:
      image: postgres
      environment:
        POSTGRES_DB: "db"
        POSTGRES_HOST_AUTH_METHOD: "trust"
      volumes:
            - data-volume:/var/lib/postgresql/data
  web-init:
      build: ./web-app
      command: /code/initserver.sh
      volumes:
        - ./web-app:/code
      depends_on:
        - db
  web:
      build: ./web-app
      user: nobody
      command: /code/runserver.sh
      volumes:
        - ./web-app:/code
      expose:
        - "8000"
      depends_on:
        - web-init
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
     depends_on: 
       - web
  backend:
    container_name: backend
    build: ./interface_server
    command: /interface_server/run_backend.sh
    volumes: 
      - ./interface_server:/interface_server
    # restart: on-failure
    expose: 
      - "45678"
    # ports: 
    #   - "45678:45678"
    depends_on: 
      - web
    
volumes:
   data-volume: 
